Module2 task3
htmlacademy-nodejs/1068207-buy-and-sell-3 pull request #5
Opened 2020-11-18 17:10 UTC by aldeimos

2020-11-18 20:18 UTC, ruslanmalogulko requested changes

2020-11-18 20:18 UTC, ruslanmalogulko commented on src/service/cli/server.js
> +  });
функция `sendResponse` пишет статус код и хедер и вроде бы этот лишний
```suggestion
```

2020-11-18 20:18 UTC, ruslanmalogulko commented on src/service/cli/server.js
> +    default: return res.end(`Упс, такой страницы нет, 404`);
а вот здесь не мешало бы записать статус код `HttpCode.NOT_FOUND` перед отправкой

2020-11-18 20:29 UTC, ruslanmalogulko commented on src/service/cli/server.js
> +  res.statusCode = statusCode;
необходимости писать statusCode, на следующей строке он пишется в методе  `.writeHead`

2020-11-21 12:03 UTC, aldeimos commented
@ruslanmalogulko done

2020-11-21 12:05 UTC, ruslanmalogulko approved these changes

2020-11-21 12:05 UTC, merged